server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;

    location /api/ {
        proxy_pass https://influ-production.up.railway.app/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host influ-production.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        proxy_pass https://influ-production.up.railway.app/static/;
        proxy_ssl_server_name on;
        proxy_set_header Host influ-production.up.railway.app;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}